import Header from '@/components/view/Header/Header';
import './globals.css'
import type { Metadata } from 'next'
import { Sora } from 'next/font/google'
import Footer from '@/components/view/Footer';
import Providers from '@/components/Providers';
import { ClerkProvider, auth } from '@clerk/nextjs'

const sora = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	const { userId } = auth();
	return (
		<>
			<ClerkProvider>
				<html lang="en">
					<body suppressHydrationWarning={true} className={`${sora.className} overflow-x-hidden bg-white`}>
						<Providers>
							<div className='flex min-h-screen flex-col '>
								<Header userId={userId as string} />
								<main className='mt-14 flex-grow flex-wrap py-4 md:mt-[88px] md:py-8 lg:mt-[110px]'>{children}</main>
								<Footer />
							</div>
						</Providers>
					</body>
				</html>
			</ClerkProvider>
		</>
	)
}
